class ReviewNotFoundError(Exception):
    pass


class ReviewAlreadyExists(Exception):
    pass
